services:
  glacier-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - /home/devj/local-arch/data/HKH/gen_robust_comprehensive:/data
      - /home/devj/local-arch/code/glacier-mapping/output:/checkpoints
    environment:
      - GRADIO_SHARE=false
      - GRADIO_HOST=0.0.0.0
      - GRADIO_PORT=7860
    restart: unless-stopped
