training_opts:
  run_name: ablation2_dci_landsat_full_physics_gpu3
  early_stopping: 30
  early_stopping_min_delta: 0.001
loader_opts:
  landsat_channels: true
  dem_channels: true
  spectral_indices_channels: false
  hsv_channels: false
  physics_channels: true
  velocity_channels: false
scheduler_opts:
  args:
    max_lr: 0.0005
