# Gen20 Variation: Low Augmentations
# Goal: Test original Gen3 low augmentation probabilities with the class weight fix.
training_opts:
  run_name: "gen20_low_augs"
loss_opts:
  class_weights: [0.01, 1]
loader_opts:
  batch_size: 16
  augmentations:
    h_flip_prob: 0.15
    v_flip_prob: 0.15
    rotate_prob: 0.15
