training_opts:
  dataset_name: "gen_robust_comprehensive"
  run_name: "gen_robust_iter6_multi_vloss_default"

loader_opts:
  batch_size: 16
  velocity_channels: true

loss_opts:
  use_velocity_loss: true
