training_opts:
  epochs: 300
  early_stopping: 35
  early_stopping_min_delta: 0.001
  mlflow_experiment_name: reproducibility2
  experiment_prefix: reproducibility2
  val_viz_n: 0
  val_viz_every_n_epochs: 0
  run_test_eval: false
  test_eval_n: 0
  deterministic: true
  seed: 42
  run_name: reproducibility2_dci_17_full_threshold_10p0_seed42
loader_opts:
  landsat_channels: true
  dem_channels: true
  spectral_indices_channels: true
  hsv_channels: true
  physics_channels: true
  velocity_channels: true
  robust_scaling: false
  output_classes:
  - 2
scheduler_opts:
  args:
    max_lr: 0.0005
loss_opts:
  use_velocity_loss: true
  velocity_high_speed_threshold: 10.0
