training_opts:
  epochs: 200
  early_stopping: 15
  early_stopping_min_delta: 0.001
  mlflow_experiment_name: reproducibility
  experiment_prefix: reproducibility
  val_viz_n: 4
  val_viz_every_n_epochs: 0
  run_test_eval: true
  test_eval_n: 4
  deterministic: true
  seed: 42
  run_name: reproducibility_dci_12_tpi_only_seed42
loader_opts:
  landsat_channels: true
  dem_channels: false
  spectral_indices_channels: false
  hsv_channels: false
  physics_channels:
  - tpi
  velocity_channels: false
  robust_scaling: false
  output_classes:
  - 2
scheduler_opts:
  args:
    max_lr: 0.0005
loss_opts:
  use_velocity_loss: false
