training_opts:
  dataset_name: "comprehensive_v3_complete_no_hsv"
  run_name: "sota_dci_24_02_timer_prefetch4_bs12_w2"
  seed: 8675309
  augmentation_seed: 1000
  deterministic: true
  epochs: 3
  early_stopping: 0
  run_test_eval: false
  test_eval_n: 0
  lr_monitor: false
  diagnostic_log_on_step: false
  timer_enabled: true

profiling_opts:
  enabled: false

loader_opts:
  batch_size: 12
  num_workers: 2
  pin_memory: true
  robust_scaling: false
  prefetch_factor: 4

loss_opts:
  use_velocity_loss: true
  velocity_loss_weight: 0.20
  velocity_high_speed_threshold: 3.16
  velocity_loss_warmup_epochs: 10
  velocity_loss_ramp_epochs: 10

model_opts:
  framework: "smp"
  name: "Unet"
  sigma_init: 0.5
  min_log_var: -3.0
  max_log_var: 2.0
  args:
    encoder_name: "resnet18"
    encoder_weights: null
