training_opts:
  dataset_name: "gen_robust_comprehensive_dci"
  run_name: "sota_dci_06_smp_unet_rn18"
  mlflow_experiment_name: "sota_replication"
  run_test_eval: true
  test_eval_n: 0
loader_opts:
  batch_size: 12
model_opts:
  framework: "smp"
  name: "Unet"
  args:
    encoder_name: "resnet18"
    encoder_weights: null
    encoder_depth: 4
    decoder_channels:
      - 128
      - 64
      - 32
      - 16
