training_opts:
  dataset_name: "gen_robust_comprehensive_dci_clean_v2"
  run_name: "sota_dci_18_06_landsat_dem_si_fullphysics_velmag_loss_w020_seed8675309"
  seed: 8675309
  augmentation_seed: 1000
  deterministic: true
  early_stopping: 35
  run_test_eval: true
  test_eval_n: 0

profiling_opts:
  enabled: true
  mode: "simple"

loader_opts:
  processed_dir: "/home/devj/local-arch/data/HKH/gen_robust_comprehensive_dci_clean_v2/"
  batch_size: 12
  landsat_channels: true
  dem_channels: true
  spectral_indices_channels: true
  hsv_channels: false
  velocity_channels: ["velocity"]
  physics_channels: true
  robust_scaling: false

loss_opts:
  use_velocity_loss: true
  velocity_loss_weight: 0.20
  velocity_high_speed_threshold: 3.16
  velocity_loss_warmup_epochs: 10
  velocity_loss_ramp_epochs: 10

model_opts:
  framework: "smp"
  name: "Unet"
  sigma_init: 0.5
  min_log_var: -3.0
  max_log_var: 2.0
  args:
    encoder_name: "resnet18"
    encoder_weights: null
