training_opts:
  dataset_name: "comprehensive_v3_landsat_dem_flowacc_velmag"
  run_name: "sota_dci_34_21_iso_logvar_wd"
  mlflow_experiment_name: "sota_replication"
  seed: 8675309
  epochs: 30
  early_stopping: 0
  run_test_eval: false
  lr_monitor: false
  progress_bar: false
  val_viz_n: 0
  test_eval_n: 0

loader_opts:
  batch_size: 12
  num_workers: 2

loss_opts:
  use_velocity_loss: true

model_opts:
  framework: "smp"
  name: "Unet"
  channels_last: true
  sigma_init: 0.5
  min_log_var: -3.0
  max_log_var: 2.0
  args:
    encoder_name: "resnet18"
    encoder_weights: null
