training_opts:
  dataset_name: gen_robust_comprehensive_notestoverlap
  epochs: 200
  mlflow_experiment_name: sota_replication
  experiment_prefix: sota_replication
  val_viz_n: 0
  val_viz_every_n_epochs: 0
  run_test_eval: true
  test_eval_n: 4
  deterministic: true
  seed: 8675309
  run_name: sota_dci_02_notestoverlap_seed8675309
loader_opts:
  landsat_channels: true
  dem_channels: true
  spectral_indices_channels: false
  hsv_channels: false
  physics_channels: false
  velocity_channels: false
  robust_scaling: false
  output_classes:
  - 2
loss_opts:
  use_velocity_loss: false
scheduler_opts:
  args:
    max_lr: 0.001
