training_opts:
  run_name: ablation2_dci_landsat_spectral_indices_gpu0
  early_stopping: 30
  early_stopping_min_delta: 0.001
loader_opts:
  landsat_channels: true
  dem_channels: false
  spectral_indices_channels: true
  hsv_channels: false
  physics_channels: false
  velocity_channels: false
scheduler_opts:
  args:
    max_lr: 0.0005
