training_opts:
  run_name: "gen22_combo_all"
model_opts:
  args:
    dropout: 0.3
loader_opts:
  augmentations:
    h_flip_prob: 0.3
    v_flip_prob: 0.3
    rotate90_prob: 0.3
    transpose_prob: 0.3
