# Inherit from the Gen6 baseline for Frodo
inherit: configs/frodo/base_gen6.yaml

training_opts:
  run_name: "gen6_ci_physics_w512"
  dataset_name: "bibek_w512_o64_f1_comprehensive_phys64_s1"

loader_opts:
  landsat_channels: true
  dem_channels: true
  spectral_indices_channels: true
  hsv_channels: true
  physics_channels: true
  velocity_channels: false
