# Base dataset (w256, o64, f1) without physics/velocity.
output_name: "bibek_w256_o64_f1_v2"

window_size: [256, 256]
overlap: 64
filter: 0.1
test: 0.2
val: 0.1

add_velocity: false
add_ndvi: false
add_ndwi: false
add_ndsi: false
add_hsv: false
physics_res: None
physics_scale: -1
save_skipped_visualizations: false
