# Config for generating the w256 non-velocity dataset
output_name: "bibek_w256_o64_f1"

# Preprocessing parameters
window_size: [256, 256]
overlap: 64
filter: 0.1
test: 0.2
val: 0.1
add_velocity: False
add_ndvi: True
add_ndwi: True
add_ndsi: True
add_hsv: True
physics_res: None
physics_scale: 1
save_skipped_visualizations: False
